using DevExpress.Xpo.Helpers;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HouseKeeping.Services.Interfaces
{
    public interface IHouseKeepingService
    {
        DataTable RoomControlPanelData(DateTime fromDate, DateTime toDate, string zone);
        DataTable RoomFacilityForecastData(DateTime fromDate, DateTime toDate, string zone);
        DataTable RoomStatusData(int cleannon_room, int clean, int dirty, int pickup, int oocheck, int oscheck, int vacant, int occupied, int arrivals, int arrived, int stayover, int dayuse, int dueout, int departed, int notReserved, int departuredarr, string roomType, string zone, string roomFrom, string roomTo);
        DataTable CheckLogStatus(string RoomNo, DateTime fromDate, DateTime toDate, string username);
        DataTable RoomPlanData(DateTime fromDate, DateTime toDate, int orderbyroom, string owner);
        DataTable SummaryTotalPhysicalRoom(string roomtype, string zone);
        DataTable StatusSummaryOutOfOrder(DateTime datebunisess, string roomtype, string zone);
        DataTable SummaryOutOfService(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityStayOver(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityDepartureExpected(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityDepartureActual(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityArrivalExpected(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityArrivalActual(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityExtendedStay(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityEarlyDeparture(DateTime datebunisess, string roomtype, string zone);
        DataTable ActivityDayUseRoom(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusHKInspected(string roomtype, string zone);
        DataTable StatusHKClean(string roomtype, string zone);
        DataTable StatusHKDirty(string roomtype, string zone);
        DataTable StatusHKOutOfOrder(string roomtype, string zone);
        DataTable StatusHKOutOfService(string roomtype, string zone);
        DataTable StatusEndOfDayGroupAndBlock(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayIndividual(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayCHU(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayMaxOccTonight(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayRoomRevenue(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayMaxOccTonightVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayIndividualVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayGroupAndBlockVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusEndOfDayCHUVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDepartureExpectedVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityStayOverVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDepartureActualVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityArrivalExpectedVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityArrivalActualVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityExtendedStayVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityEarlyDepartureVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDayUseRoomVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityWakeInRoomVIP(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityWalkInRoom(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusSummaryOutOfOrderDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusSummaryOutOfServiceDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityStayOverDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDepartureExpectedDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDepartureActualDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityArrivalExpectedDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityArrivalActualDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityExtendedStayDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityEarlyDepartureDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityDayUseRoomDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusActivityWalkInRoomDetail(DateTime datebunisess, string roomtype, string zone);
        DataTable StatusHKVacantCleanDetail(string roomtype, string zone);
        DataTable StatusHKInspectedOCCDetail(string roomtype, string zone);
        DataTable StatusHKVCNDetail(string roomtype, string zone);
        DataTable StatusHKCleanOCCDetail(string roomtype, string zone);
        DataTable StatusActivityDueOutDetail(string roomtype, string zone);
        DataTable StatusHKVacantDirtyDetail(string roomtype, string zone);
        DataTable StatusHKDirtyOCCDetail(string roomtype, string zone);
        DataTable StatusHKOutOfOrderVacantDetail(string roomtype, string zone);
        DataTable StatusHKOutOfServiceVacantDetail(string roomtype, string zone);
        DataTable StatusHKOutOfServiceOCCDetail(string roomtype, string zone);
        DataTable GuestServiceStatusData(string servicestatsu, string room, string roomStatus, string zone);
        DataTable TaskSheetStatusData(DateTime fromDate, DateTime toDate, string attendant, string room, string zone);
        DataTable TaskAssignmentData(DateTime fromDate, string tasksheet, string zone);
        DataTable RoomAttendantDailyWorkSheet(DateTime fromDatere, DateTime toDatere, string taskcodeexpan, string attendantrepop, string tasksheetpopre, string dueoutonly);
        DataTable RAWorkSheet(DateTime fromDatere, DateTime toDatere, string taskcodeexpan, string attendantrepop, string tasksheetpopre, string dueoutonly);
        DataTable SupChecklistFloor(DateTime fromDatere, DateTime toDatere, string taskcodeexpan, string attendantrepop, string tasksheetpopre, string dueoutonly);
        DataTable ViewTurnDown(string roomTypead, string sectionAd, string zoneAd, string fromRoom, string toRoom, string HKStatusID, string ReservationStatus, string arrived, string turndownStatus);
        DataTable TasksheetDetailsSearch(int ID);
        DataTable RoomAttendentDailyWorksheetData(DateTime fromDate, string attendant, string tasksheet, string roomStatus, string facilityCode);
        DataTable TurndownTasksheet(DateTime fromDate, string attendant, string roomStatus);
        DataTable TasksheetAutomatically(string HK_FO, DateTime taskdateauto, string floorauto, string roomTypeauto, string zonecodeauto, string subzonecodeauto, string includeroomAS, string arrivalOnly, string _ListRoomNotAss);
        DataTable TurndownTasksheetData(DateTime fromDate, string attendant, string IsDueOut, string roomStatus);
        DataTable AutoMakeupServiceRoom(string roomIDs, string _ListSection);
        DataTable LostAndFound(DateTime fromDate, DateTime toDate);
        DataTable HKPGetTaskSheets(DateTime BusinessDate, int  page, string zoneexpan, string taskcodeExpanded, string hkpSectionExpanded);
        DataTable HKPTurndownTaskSheetGrid(string  taskid, string status);
        DataTable RoomAvailabilityData(DateTime fromDate, DateTime toDate, string zone, string columnsString, string expressionString,string idList,string includeOverbooking,string stringincludeAllotment);
        DataTable GetRoomByAllotment(DateTime fromDate, DateTime toDate, string zone, string columnsString, string expressionString, string idList, string includeOverbooking, string stringincludeAllotment);
        DataTable GetBookedRoom(DateTime fromDate, DateTime toDate, string zone, string columnsString, string expressionString, string idList, string includeOverbooking, string stringincludeAllotment);
        DataTable SelectAvailibilityColor(DateTime fromDate, DateTime toDate);
    }

}
