using BaseBusiness.bc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BaseBusiness.Model
{
    public class ReservationModel : BaseModel
    {
        public int ID { get; set; }
        public string ConfirmationNo { get; set; }
        public string ReservationNo { get; set; }
        public DateTime ReservationDate { get; set; }
        public int ProfileAgentId { get; set; }
        public string AgentName { get; set; }
        public int ProfileCompanyId { get; set; }
        public string CompanyName { get; set; }
        public int ProfileSourceId { get; set; }
        public string SourceName { get; set; }
        public int ProfileGroupId { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public int ProfileContactId { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ProfileComment { get; set; }
        public int ProfileIndividualId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string MemberType { get; set; }
        public string MemberNo { get; set; }
        public string MemberLevel { get; set; }
        public int VipId { get; set; }
        public string Vip { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Language { get; set; }
        public DateTime ArrivalDate { get; set; }
        public DateTime OriginalArrivalDate { get; set; }
        public int NoOfNight { get; set; }
        public DateTime DepartureDate { get; set; }
        public DateTime OriginalDepartureDate { get; set; }
        public int NoOfAdult { get; set; }
        public int NoOfChild { get; set; }
        public int NoOfChild1 { get; set; }
        public int NoOfChild2 { get; set; }
        public int NoOfRoom { get; set; }
        public int RoomTypeId { get; set; }
        public string RoomType { get; set; }
        public int RtcId { get; set; }
        public int RoomId { get; set; }
        public string RoomNo { get; set; }
        public int BusinessBlockId { get; set; }
        public string BusinessBlockCode { get; set; }
        public string Eta { get; set; }
        public DateTime CheckInDate { get; set; }
        public string Etd { get; set; }
        public DateTime CheckOutDate { get; set; }
        public int ReservationTypeId { get; set; }
        public string ReservationTypeCode { get; set; }
        public int MarketId { get; set; }
        public string MarketCode { get; set; }
        public int SourceId { get; set; }
        public string SourceCode { get; set; }
        public int OriginId { get; set; }
        public string OriginCode { get; set; }
        public string CCHolder { get; set; }
        public int BookerId { get; set; }
        public string BookerName { get; set; }
        public string BookerDetails { get; set; }
        public bool NoPost { get; set; }
        public bool PrintRate { get; set; }
        public bool ConfirmationStatus { get; set; }
        public bool VideoCheckOutStatus { get; set; }
        public string CRSNo { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal DiscountRate { get; set; }
        public string DiscountReason { get; set; }
        public string Comment { get; set; }
        public decimal BalanceUSD { get; set; }
        public decimal BalanceVND { get; set; }
        public string ApprovalCode { get; set; }
        public decimal ApprovalAmount { get; set; }
        public string SuiteWith { get; set; }
        public string PaymentMethod { get; set; }
        public string CreditCardNo { get; set; }
        public DateTime ExpirationDate { get; set; }
        public int TaxTypeId { get; set; }
        public string ExemptNumber { get; set; }
        public int PickupReqdId { get; set; }
        public string PickupTransportType { get; set; }
        public string PickupStationCode { get; set; }
        public string PickupCarrierCode { get; set; }
        public string PickupTime { get; set; }
        public string PickupTransportNo { get; set; }
        public DateTime PickupArrivalDate { get; set; }
        public string PickupDescription { get; set; }
        public int DropOffReqdId { get; set; }
        public string DropOffTransportType { get; set; }
        public string DropOffStationCode { get; set; }
        public string DropOffCarrierCode { get; set; }
        public string DropOffTime { get; set; }
        public string DropOffTransportNo { get; set; }
        public DateTime DropOffDepartureDate { get; set; }
        public string DropOffDescription { get; set; }
        public int PackageId { get; set; }
        public string Packages { get; set; }
        public int Relationship { get; set; }
        public int Status { get; set; }
        public bool PostingMaster { get; set; }
        public bool MainGuest { get; set; }
        public int RateCodeId { get; set; }
        public string RateCode { get; set; }
        public decimal Rate { get; set; }
        public decimal RateAfterTax { get; set; }
        public bool FixedRate { get; set; }
        public decimal TotalAmount { get; set; }
        public string CurrencyId { get; set; }
        public string Party { get; set; }
        public string PartyGuest { get; set; }
        public bool IsPasserBy { get; set; }
        public string Color { get; set; }
        public string ARNo { get; set; }
        public string ItemInventory { get; set; }
        public string Specials { get; set; }
        public int ShareRoom { get; set; }
        public bool NoShowStatus { get; set; }
        public string ShareRoomName { get; set; }
        public string AccompanyName { get; set; }
        public string RoutingTransaction { get; set; }
        public string RoutingToProfile { get; set; }
        public string FixedCharge { get; set; }
        public string CommentGroup { get; set; }
        public bool IsWalkIn { get; set; }
        public int UserInsertId { get; set; }
        public DateTime CreateDate { get; set; }
        public int UserUpdateId { get; set; }
        public DateTime UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string SpecialUpdateBy { get; set; }
        public DateTime SpecialUpdateDate { get; set; }
        public bool IsAdvanceBill { get; set; }
        public string DepositPayment { get; set; }
        public string DepositRequest { get; set; }
        public int AllotmentId { get; set; }
        public string AllotmentCode { get; set; }
        public string PinCode { get; set; }
        public string KeyRoomStatus { get; set; }
        public int PersonInChargeId { get; set; }
        public int RoomNight { get; set; }
        public string CardId { get; set; }
        public bool Breakfast { get; set; }
        public bool Dinner { get; set; }
        public bool Lunch { get; set; }
        public bool FixedMeal { get; set; }
        public string VoucherId { get; set; }
        public decimal GuestSN { get; set; }
        public decimal AmountMeal { get; set; }
        public bool IsWeb { get; set; }
        public string WebName { get; set; }
        public int StatusTransfer { get; set; }
    }
}
